version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/ec2-instance

hooks:
  BeforeInstall:
    - location: console/update_repo.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: console/run_php_script.sh
      timeout: 300
      runas: root
