version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/ec2-instance
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: console/setup_files.sh
      timeout: 300
      runas: root
